language: generic
# sudo: required
os: linux

services:
  - docker

before_install :
  - docker build -t vishal/docker-reactjs -f Dockerfile.dev .

script : 
  - docker run vishal/docker-reactjs npm run test -- --coverage