language: generic
# sudo: required
os: linux

services:
  - docker

before_install :
  - docker build -t vishal/docker-reactjs -f Dockerfile.dev .

script : 
  - docker run -e CI=true vishal/docker-reactjs npm run test -- --coverage

deploy :
  provider : elasticbeanstalk
  region : "us-east-1"
  app : "docker-reactjs"
  env : "DockerReactjs-env"
  bucket_name : "elasticbeanstalk-us-east-1-671822208157"
  bucket_path : "docker-reactjs"
  on:
    branch : master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET